# Generated by Django 3.1.6 on 2021-02-16 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20210216_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='member',
        ),
        migrations.AddField(
            model_name='list',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
